# Generated by Django 6.0.4 on 2026-04-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='gemini_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
