# Generated by Django 6.0.4 on 2026-04-18 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatsession_gemini_file_name'),
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='document',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='gemini_file_name',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='chat_sessions', to='materials.document'),
        ),
        migrations.CreateModel(
            name='GeminiFileCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.document')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_caches', to='chat.chatsession')),
            ],
            options={
                'unique_together': {('session', 'document')},
            },
        ),
    ]
