# Generated by Django 6.0.4 on 2026-04-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_chatsession_document_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeminiFileCache',
        ),
    ]
