# Generated by Django 6.0.4 on 2026-04-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_generationusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
